// This file is a modified version of the original generated by the project template.
// It has been updated to support Phase 4 of the roadmap.

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../../core/services/local_storage_service.dart';
import '../../../../core/presentation/widgets/metallic_card.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../auth/presentation/bloc/auth_bloc.dart';
import '../../../auth/presentation/bloc/auth_event.dart';
import 'acta_form_page.dart';

class MisMesasPage extends StatelessWidget {
  const MisMesasPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final session = LocalStorageService.sessionBox.get('current');
    final recintoId = session?.recintoId ?? 'No asignado';
    final mesaId = session?.mesaId ?? 'No asignada';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Mis Mesas'),
        flexibleSpace: Container(
          decoration: BoxDecoration(
            gradient: AppColors.metallicGradient,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Cerrar sesión',
            onPressed: () => context.read<AuthBloc>().add(LogoutRequested()),
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              MetallicCard(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          const Icon(Icons.table_bar_rounded, size: 28, color: AppColors.accent),
                          const SizedBox(width: 8),
                          Text(
                            'Mesa N°$mesaId',
                            style: theme.textTheme.headlineSmall?.copyWith(color: Colors.white),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Recinto: $recintoId',
                        style: theme.textTheme.bodyMedium?.copyWith(
                              color: Colors.white70,
                            ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              Text(
                'Registrar Acta de Escrutinio',
                style: theme.textTheme.titleMedium,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: AppColors.metallicGradient,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: AppColors.accent, width: 1.5),
                      ),
                      child: FilledButton.icon(
                        onPressed: () => _navegarActa(context, 'alcalde'),
                        icon: const Icon(Icons.how_to_vote, color: Colors.white),
                        label: const Text('Acta Alcalde', style: TextStyle(color: Colors.white)),
                        style: FilledButton.styleFrom(
                          backgroundColor: Colors.transparent,
                          shadowColor: Colors.transparent,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: AppColors.metallicGradient,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: AppColors.accent, width: 1.5),
                      ),
                      child: FilledButton.icon(
                        onPressed: () => _navegarActa(context, 'prefecto'),
                        icon: const Icon(Icons.how_to_vote_outlined, color: Colors.white),
                        label: const Text('Acta Prefecto', style: TextStyle(color: Colors.white)),
                        style: FilledButton.styleFrom(
                          backgroundColor: Colors.transparent,
                          shadowColor: Colors.transparent,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _navegarActa(BuildContext context, String tipo) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ActaFormPage(tipo: tipo),
      ),
    );
  }
}
