// This file is a modified version of the original generated by the project template.
// It has been updated to support Phase 4 of the roadmap.

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:appwrite/appwrite.dart' as appwrite_sdk;
import '../../../../core/services/appwrite_service.dart';
import '../../domain/entities/acta_escrutinio_local_entity.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../../core/services/local_storage_service.dart';
import '../../../../core/presentation/widgets/metallic_card.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../auth/presentation/bloc/auth_bloc.dart';
import '../../../auth/presentation/bloc/auth_event.dart';
import 'acta_form_page.dart';

class MisMesasPage extends StatelessWidget {
  const MisMesasPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final session = LocalStorageService.sessionBox.get('current');
    final recintoId = session?.recintoId ?? 'No asignado';
    final mesaId = session?.mesaId ?? 'No asignada';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Mis Mesas'),
        flexibleSpace: Container(
          decoration: BoxDecoration(
            gradient: AppColors.metallicGradient,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Cerrar sesión',
            onPressed: () => context.read<AuthBloc>().add(LogoutRequested()),
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              MetallicCard(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          const Icon(Icons.table_bar_rounded, size: 28, color: AppColors.accent),
                          const SizedBox(width: 8),
                          Text(
                            'Mesa N°$mesaId',
                            style: theme.textTheme.headlineSmall?.copyWith(color: Colors.white),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Recinto: $recintoId',
                        style: theme.textTheme.bodyMedium?.copyWith(
                              color: Colors.white70,
                            ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              Text(
                'Registrar Acta de Escrutinio',
                style: theme.textTheme.titleMedium,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: AppColors.metallicGradient,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: AppColors.accent, width: 1.5),
                      ),
                      child: FilledButton.icon(
                        onPressed: () => _navegarActa(context, 'alcalde', recintoId, mesaId),
                        icon: const Icon(Icons.how_to_vote, color: Colors.white),
                        label: const Text('Acta Alcalde', style: TextStyle(color: Colors.white)),
                        style: FilledButton.styleFrom(
                          backgroundColor: Colors.transparent,
                          shadowColor: Colors.transparent,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: AppColors.metallicGradient,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: AppColors.accent, width: 1.5),
                      ),
                      child: FilledButton.icon(
                        onPressed: () => _navegarActa(context, 'prefecto', recintoId, mesaId),
                        icon: const Icon(Icons.how_to_vote_outlined, color: Colors.white),
                        label: const Text('Acta Prefecto', style: TextStyle(color: Colors.white)),
                        style: FilledButton.styleFrom(
                          backgroundColor: Colors.transparent,
                          shadowColor: Colors.transparent,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _navegarActa(BuildContext context, String tipo, String recintoId, String mesaId) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Center(child: CircularProgressIndicator()),
    );

    Map<String, dynamic>? existingData;

    try {
      final appwrite = AppwriteService();
      final docs = await appwrite.databases.listDocuments(
        databaseId: appwrite.databaseId,
        collectionId: appwrite.actasCollectionId,
        queries: [
          appwrite_sdk.Query.equal('recinto_id', recintoId),
          appwrite_sdk.Query.equal('id_jrv', mesaId),
          appwrite_sdk.Query.equal('dignidad', tipo),
        ],
      );

      if (docs.documents.isNotEmpty) {
        existingData = docs.documents.first.data;
        // The data is a map. Wait, votos_partidos is a JSON string in Appwrite!
        if (existingData['votos_partidos'] is String) {
          existingData['votos_partidos'] = jsonDecode(existingData['votos_partidos']);
        }
      }
    } catch (e) {
      // Offline fallback: check Hive
      final actasLocales = LocalStorageService.actasLocalesBox.values.toList();
      try {
        final localActa = actasLocales.firstWhere(
          (a) => a.recintoId == recintoId && a.mesaId == mesaId && a.tipo == tipo,
        );
        existingData = {
          'votos_partidos': { for (var v in localActa.votosPartidos) v.nombreOrganizacion: v.cantidadVotos },
          'votos_blancos': localActa.votosBlancos,
          'votos_nulos': localActa.votosNulos,
          'total_sufragantes': localActa.totalSufragantes,
        };
      } catch (_) {
        // Not found locally
      }
    }

    if (context.mounted) {
      Navigator.pop(context); // close loading

      if (existingData != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Esta acta ya fue enviada. Modo de Solo Lectura.'),
            backgroundColor: AppColors.accent,
          ),
        );
      }

      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => ActaFormPage(
            tipo: tipo,
            isReadOnly: existingData != null,
            initialData: existingData,
          ),
        ),
      );
    }
  }
}
