// This file is a modified version of the original generated by the project template.
// It has been updated to support Phase 4 of the roadmap.

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:appwrite/appwrite.dart' as appwrite_sdk;
import '../../../../core/services/appwrite_service.dart';
import '../../domain/entities/acta_escrutinio_local_entity.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../../core/services/local_storage_service.dart';
import '../../../../core/presentation/widgets/premium_card.dart';
import '../../../../core/presentation/widgets/premium_scaffold.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../auth/presentation/bloc/auth_bloc.dart';
import '../../../auth/presentation/bloc/auth_event.dart';
import 'acta_form_page.dart';

class MisMesasPage extends StatelessWidget {
  const MisMesasPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final session = LocalStorageService.sessionBox.get('current');
    final recintoId = session?.recintoId ?? 'No asignado';
    final mesaId = session?.mesaId ?? 'No asignada';

    return PremiumScaffold(
      title: 'Mis Mesas',
      subtitle: 'Registra y corrige actas de escrutinio',
      showBackButton: false,
      actions: [
        IconButton(
          icon: const Icon(Icons.logout, color: Colors.white),
          tooltip: 'Cerrar sesión',
          onPressed: () => context.read<AuthBloc>().add(LogoutRequested()),
        ),
      ],
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            PremiumCard(
              hasDecoration: true,
              decorationColor: AppColors.primary.withOpacity(0.05),
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        const CircleAvatar(
                          backgroundColor: AppColors.primary,
                          child: Icon(Icons.table_bar_rounded, size: 24, color: Colors.white),
                        ),
                        const SizedBox(width: 12),
                        Text(
                          'Mesa N°$mesaId',
                          style: theme.textTheme.headlineSmall?.copyWith(
                            color: theme.colorScheme.onSurface,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'Recinto: $recintoId',
                      style: theme.textTheme.bodyMedium?.copyWith(
                            color: Colors.black54,
                          ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 32),
            Text(
              'Registrar Acta de Escrutinio',
              style: theme.textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: FilledButton.icon(
                    onPressed: () => _navegarActa(context, 'alcalde', recintoId, mesaId),
                    icon: const Icon(Icons.how_to_vote),
                    label: const Text('Alcalde'),
                    style: FilledButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      backgroundColor: AppColors.primary,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: FilledButton.icon(
                    onPressed: () => _navegarActa(context, 'prefecto', recintoId, mesaId),
                    icon: const Icon(Icons.how_to_vote),
                    label: const Text('Prefecto'),
                    style: FilledButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      backgroundColor: AppColors.secondary,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  void _navegarActa(BuildContext context, String tipo, String recintoId, String mesaId) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Center(child: CircularProgressIndicator()),
    );

    Map<String, dynamic>? existingData;

    try {
      final appwrite = AppwriteService();
      final docs = await appwrite.databases.listDocuments(
        databaseId: appwrite.databaseId,
        collectionId: appwrite.actasCollectionId,
        queries: [
          appwrite_sdk.Query.equal('recinto_id', recintoId),
          appwrite_sdk.Query.equal('id_jrv', mesaId),
          appwrite_sdk.Query.equal('dignidad', tipo),
        ],
      );

      if (docs.documents.isNotEmpty) {
        existingData = docs.documents.first.data;
        // The data is a map. Wait, votos_partidos is a JSON string in Appwrite!
        if (existingData['votos_partidos'] is String) {
          existingData['votos_partidos'] = jsonDecode(existingData['votos_partidos']);
        }
      }
    } catch (e) {
      // Offline fallback: check Hive
      final actasLocales = LocalStorageService.actasLocalesBox.values.toList();
      try {
        final localActa = actasLocales.firstWhere(
          (a) => a.recintoId == recintoId && a.mesaId == mesaId && a.tipo == tipo,
        );
        existingData = {
          'votos_partidos': { for (var v in localActa.votosPartidos) v.nombreOrganizacion: v.cantidadVotos },
          'votos_blancos': localActa.votosBlancos,
          'votos_nulos': localActa.votosNulos,
          'total_sufragantes': localActa.totalSufragantes,
        };
      } catch (_) {
        // Not found locally
      }
    }

    if (context.mounted) {
      Navigator.pop(context); // close loading

      if (existingData != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Esta acta ya fue enviada. Puedes modificarla si es necesario.'),
            backgroundColor: AppColors.accent,
          ),
        );
      }

      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => ActaFormPage(
            tipo: tipo,
            recintoId: recintoId,
            mesaId: mesaId,
            isReadOnly: false,
            initialData: existingData,
          ),
        ),
      );
    }
  }
}
